apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: rbx
  name: rbx
spec:
  containers:
  - image: nginx
    name: rbx
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}